### ISSUE TITLE
什么傻逼东西，还是个二次元，我要笑死

### ISSUE THREAD

**Issue by hktiy** [histion/webui-galgame-lora#1]

**Comment by histion** [comment]
什么傻逼东西，还不敢上大号只敢小号在这里当个废狗米猴来找扇脸

**Comment by histion** [comment]
你像极了替皇帝急眼的小太监🤣

**Comment by histion** [comment]
你的妈妈在当楼凤赚的钱够你给你雷猴主子尽孝吗？不买su7开除你米籍！

**Comment by histion** [comment]
什么傻逼东西，还是个猴子猴孙，我要笑死

**Comment by histion** [comment]
&#129313;马戏团里你最忙，哥谭市里你最狂。&#129313;

&#129313;麦当劳前你站岗，扑克牌里大小王。&#129313;

**Comment by histion** [comment]
第一次见蚊虫自己把脸丢上来找扇的😝

**Comment by histion** [comment]
有澎湃OS吗？有AI狂暴引擎吗？有2K屏吗？有冰封循环冷泵吗？有超窄视觉四等边直屏吗？有全等深微曲屏吗？有71.5mm黄金尺寸设计吗？有高能密度碳硅电池吗？有澎湃电池管理系统吗？有莱卡光学莱卡summilux镜头莱卡浮动长焦莱卡超广角吗？有无极可变光圈吗？有小米影像大脑吗？有龙晶玻璃吗？有第三代ESA技术的定制马达吗。有王一博吗？销量不到k70的零头，别扯了。
